# @author	Jon Hourany
# @date		10/23/2013
# @file		Makefile
# 
# @class	EECE 555
# @term		Fall 2013
#
# @breif	This make file is insteaded for use on program 3. To use, first install
#		libpcap. 

all: arp_resolver 

arp_resolver: arp_resolver.c
	gcc -g arp_resolver.c -Wall -o arp_resolver -lpcap

