##
 # @authors	Jacob Young, Jon Hourany
 # @date	09/10/13
 # @file	Makefile
 #
 # @brief	lab2 
##
all: server client

server: stream-talk-server.c
	gcc -Wall -o server stream-talk-server.c
	
client: stream-talk-client.c
	gcc -Wall -o client stream-talk-client.c
 