# Author: Jacob Young, Jon Hourany
# Date Last Modified: 09/17/2013

# EECE 555
# Spring 2013

all: 

client: stream-talk-client.c 
	gcc -Wall -o stream-talk-client.c client

server: stream-talkserver.c
	gcc -Wall -o stream-talk-server.c server
 
